repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.252
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --select, "F,E,W,I,N,PL"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.8.1
    hooks:
      - id: snakefmt
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
